name: "Mirror To Github Wiki"

on:
    push:
        branches:
            - main
        paths:
            - "src/docs/**"

concurrency:
    group: publish-wiki
    cancel-in-progress: true

permissions:
    contents: write

jobs:
    Mirror:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v6
            - name: "Upload Documentation to Wiki"
              uses: Andrew-Chen-Wang/github-wiki-action@v5
              with:
                  repository: "Sleeper-Society/HDC-Wishgranter"
                  path: "src/docs"
